### ISSUE TITLE
I have no clue what i'm doing and I need help

### ISSUE THREAD

**Issue by SquidyProductions** [tnovas/youtube#1]
Ok so on your youtube stream API there is this variable called 'youtube'. I am confused on how this all works so I would like so assistance in that process.

**Comment by tnovas** [comment]
Hello, first you need registry an applicacion on Youtube here is the link https://developers.google.com/youtube/registering_an_application, once you have the creedentials you must by call the api with the params, did you see the documentation? https://github.com/tnovas/youtube/blob/master/README.md
